spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///test
    username: root
    password: 123456
  thymeleaf:
    cache: false
  redis:
    url: redis://localhost:6379
    
    
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.cloris.domain
  mapper-locations:
  - classpath:mapper/*.xml
